services:
  # the cms
  - type: web
    plan: starter
    # region: frankfurt # need to get upgrade
    numInstances: 1
    name: joshuacurtis-portfolio-cms
    rootDir: cms
    runtime: node
    branch: master
    buildCommand: npm install && npm run build
    startCommand: rsync -a public/ /data/public/ && npm start
    healthCheckPath: /_health
    autoDeploy: true
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 20
    envVars:
      - key: NODE_VERSION
        value: 21.6.2
      - key: NODE_ENV
        value: production
      - key: HOST_URL
        value: https://cms.joshuacurtis.dev
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: DATABASE_CLIENT
        value: sqlite
      - key: DATABASE_FILENAME
        value: /data/strapi.db
      - key: PUBLIC_PATH
        value: /data/public
  # the web app
  - type: web
    name: joshuacurtis-portfolio-app
    rootDir: app
    runtime: static
    branch: master
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    healthCheckPath: /_health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 21.6.2
      - key: NODE_ENV
        value: production
      - key: VITE_STRAPI_HOST
        value: https://cms.joshuacurtis.dev
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
